name: BukkitLTI
main: com.instructure.bukkitlti.BukkitLTI
version: 0.5.3
commands:
   register:
      description: Associate an LTI user with your player
      usage: /register [token]
   assignment:
      description: Begin, submit, or configure an assignment
      usage: /assignment [begin|submit|set]
   grade:
      description: Record a grade for a student
      usage: /grade @p 0.9
   instructor:
      description: Toggle whether a user is an instructor
      usage: /instructor [username]
